### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by RWOverdijk** [apolkingg8/React-Native-Swipeable-Modal#6]
It could be me, but I did a checkout and install.. And got this:

https://www.dropbox.com/s/i99c1qb1rprt654/Screenshot%202015-08-13%2021.26.17.png?dl=0

**Comment by RWOverdijk** [comment]
Update: I also noticed it's depending on an outdated version of react-native. If there's any way I can help, let me know!

**Comment by apolkingg8** [comment]
@RWOverdijk Thanks for point that! I did some stupid things in example and now it fixed. About the dependencies, I'll remove `underscore` this weekend because it's seams redundancy, but `"react-native": ">=0.5.0"` is fine. I don't (and can't) replace `LayoutAnimation` with `Animated` because it more smooth when dragging, so there seams no need to update dependence to `>=0.8.0` or upper version. Feel free to new Issue if you have ideal with that! :beer:

**Comment by RWOverdijk** [comment]
Cheers, thanks! And alright. Is the react community aware of this animation issue? I believe it should be tackled so that this module can work with the latest version. I'd love to help wherever possible :)

**Comment by apolkingg8** [comment]
@RWOverdijk maybe my English is too poor to clear describe that :crying_cat_face: . I think it works fine with latest stable version because I'm using it with `React-Native 0.8.0` in my official project, and `0.8.0 >= 0.5.0` is true so npm should not warn or error with that. Please let me know if you got any error or warn with some version.

**Comment by RWOverdijk** [comment]
Oh! Sorry. Thanks!
